version: '3'

services:
  vue-app:
    container_name: iut_front_vue
    restart: on-failure
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "3001:3001"